// GoTG Generic Helpers
// WARNING: This file is autogenerated, please DO NOT EDIT

package generic

import (
	"github.com/gotd/td/tg"
	"github.com/pageton/gotg/adapter"
	"github.com/pageton/gotg/types"
)

type ChatUnion interface {
	int | int64 | string
}

func getIdByUnion[chatUnion ChatUnion](ctx *adapter.Context, chat chatUnion) (int64, error) {
	switch val := any(chat).(type) {
	case string:
		username := val
		peer := ctx.PeerStorage.GetPeerByUsername(username)
		if peer.ID != 0 {
			return peer.ID, nil
		}
		chat, err := ctx.ResolveUsername(username)
		return chat.GetID(), err
	case int64:
		return val, nil
	case int:
		return int64(val), nil
	}
	// Unreachable
	return 0, nil
}

// SendMessage is a generic helper for adapter.Context.SendMessage method.
func SendMessage[chatUnion ChatUnion](ctx *adapter.Context, chat chatUnion, request *tg.MessagesSendMessageRequest) (*types.Message, error) {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return nil, err
	}

	return ctx.SendMessage(chatID, request)
}

// SendMedia is a generic helper for adapter.Context.SendMedia method.
func SendMedia[chatUnion ChatUnion](ctx *adapter.Context, chat chatUnion, request *tg.MessagesSendMediaRequest) (*types.Message, error) {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return nil, err
	}

	return ctx.SendMedia(chatID, request)
}

// SendReaction is a generic helper for adapter.Context.SendReaction method.
func SendReaction[chatUnion ChatUnion](ctx *adapter.Context, chat chatUnion, request *tg.MessagesSendReactionRequest) (*types.Message, error) {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return nil, err
	}

	return ctx.SendReaction(chatID, request)
}

// SendMultiMedia is a generic helper for adapter.Context.SendMultiMedia method.
func SendMultiMedia[chatUnion ChatUnion](ctx *adapter.Context, chat chatUnion, request *tg.MessagesSendMultiMediaRequest) (*types.Message, error) {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return nil, err
	}

	return ctx.SendMultiMedia(chatID, request)
}

// EditMessage is a generic helper for adapter.Context.EditMessage method.
func EditMessage[chatUnion ChatUnion](ctx *adapter.Context, chat chatUnion, request *tg.MessagesEditMessageRequest) (*types.Message, error) {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return nil, err
	}

	return ctx.EditMessage(chatID, request)
}

// EditCaption is a generic helper for adapter.Context.EditCaption method.
func EditCaption[chatUnion ChatUnion](ctx *adapter.Context, chat chatUnion, messageID int, caption string, entities []tg.MessageEntityClass) (*types.Message, error) {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return nil, err
	}

	return ctx.EditCaption(chatID, messageID, caption, entities)
}

// EditReplyMarkup is a generic helper for adapter.Context.EditReplyMarkup method.
func EditReplyMarkup[chatUnion ChatUnion](ctx *adapter.Context, chat chatUnion, messageID int, markup tg.ReplyMarkupClass) (*types.Message, error) {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return nil, err
	}

	return ctx.EditReplyMarkup(chatID, messageID, markup)
}

// GetChat is a generic helper for adapter.Context.GetChat method.
func GetChat[chatUnion ChatUnion](ctx *adapter.Context, chat chatUnion) (tg.ChatFullClass, error) {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return nil, err
	}

	return ctx.GetChat(chatID)
}

// GetUser is a generic helper for adapter.Context.GetUser method.
func GetUser[chatUnion ChatUnion](ctx *adapter.Context, user chatUnion) (*tg.UserFull, error) {

	userID, err := getIdByUnion(ctx, user)
	if err != nil {
		return nil, err
	}

	return ctx.GetUser(userID)
}

// GetChatMember is a generic helper for adapter.Context.GetChatMember method.
func GetChatMember[chatUnion ChatUnion](ctx *adapter.Context, chat, user chatUnion) (*types.Participant, error) {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return nil, err
	}

	userID, err := getIdByUnion(ctx, user)
	if err != nil {
		return nil, err
	}

	return ctx.GetChatMember(chatID, userID)
}

// GetMessages is a generic helper for adapter.Context.GetMessages method.
func GetMessages[chatUnion ChatUnion](ctx *adapter.Context, chat chatUnion, messageIDs []tg.InputMessageClass) ([]tg.MessageClass, error) {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return nil, err
	}

	return ctx.GetMessages(chatID, messageIDs)
}

// BanChatMember is a generic helper for adapter.Context.BanChatMember method.
func BanChatMember[chatUnion ChatUnion](ctx *adapter.Context, chat, user chatUnion, untilDate int) (tg.UpdatesClass, error) {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return nil, err
	}

	userID, err := getIdByUnion(ctx, user)
	if err != nil {
		return nil, err
	}

	return ctx.BanChatMember(chatID, userID, untilDate)
}

// UnbanChatMember is a generic helper for adapter.Context.UnbanChatMember method.
func UnbanChatMember[chatUnion ChatUnion](ctx *adapter.Context, chat, user chatUnion) (bool, error) {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return false, err
	}

	userID, err := getIdByUnion(ctx, user)
	if err != nil {
		return false, err
	}

	return ctx.UnbanChatMember(chatID, userID)
}

// AddChatMembers is a generic helper for adapter.Context.AddChatMembers method.
func AddChatMembers[chatUnion ChatUnion](ctx *adapter.Context, chat chatUnion, userIDs []int64, forwardLimit int) (bool, error) {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return false, err
	}

	return ctx.AddChatMembers(chatID, userIDs, forwardLimit)
}

// DeleteMessages is a generic helper for adapter.Context.DeleteMessages method.
func DeleteMessages[chatUnion ChatUnion](ctx *adapter.Context, chat chatUnion, messageIDs []int) error {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return err
	}

	return ctx.DeleteMessages(chatID, messageIDs)
}

// PromoteChatMember is a generic helper for adapter.Context.PromoteChatMember method.
func PromoteChatMember[chatUnion ChatUnion](ctx *adapter.Context, chat, user chatUnion, opts *adapter.EditAdminOpts) (bool, error) {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return false, err
	}

	userID, err := getIdByUnion(ctx, user)
	if err != nil {
		return false, err
	}

	return ctx.PromoteChatMember(chatID, userID, opts)
}

// DemoteChatMember is a generic helper for adapter.Context.DemoteChatMember method.
func DemoteChatMember[chatUnion ChatUnion](ctx *adapter.Context, chat, user chatUnion, opts *adapter.EditAdminOpts) (bool, error) {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return false, err
	}

	userID, err := getIdByUnion(ctx, user)
	if err != nil {
		return false, err
	}

	return ctx.DemoteChatMember(chatID, userID, opts)
}

// GetUserProfilePhotos is a generic helper for adapter.Context.GetUserProfilePhotos method.
func GetUserProfilePhotos[chatUnion ChatUnion](ctx *adapter.Context, user chatUnion, opts *tg.PhotosGetUserPhotosRequest) ([]tg.PhotoClass, error) {

	userID, err := getIdByUnion(ctx, user)
	if err != nil {
		return nil, err
	}

	return ctx.GetUserProfilePhotos(userID, opts)
}

// TransferStarGift is a generic helper for adapter.Context.TransferStarGift method.
func TransferStarGift[chatUnion ChatUnion](ctx *adapter.Context, chat chatUnion, starGift tg.InputSavedStarGiftClass) (tg.UpdatesClass, error) {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return nil, err
	}

	return ctx.TransferStarGift(chatID, starGift)
}

// PinMessage is a generic helper for adapter.Context.PinMessage method.
func PinMessage[chatUnion ChatUnion](ctx *adapter.Context, chat chatUnion, messageID int) (tg.UpdatesClass, error) {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return nil, err
	}

	return ctx.PinMessage(chatID, messageID)
}

// UnpinMessage is a generic helper for adapter.Context.UnpinMessage method.
func UnpinMessage[chatUnion ChatUnion](ctx *adapter.Context, chat chatUnion, messageID int) error {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return err
	}

	return ctx.UnpinMessage(chatID, messageID)
}

// UnpinAllMessages is a generic helper for adapter.Context.UnpinAllMessages method.
func UnpinAllMessages[chatUnion ChatUnion](ctx *adapter.Context, chat chatUnion) error {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return err
	}

	return ctx.UnpinAllMessages(chatID)
}
