// GoTG Generic Helpers
// WARNING: This file is autogenerated, please DO NOT EDIT

package generic

import (
	"github.com/gotd/td/tg"
	"github.com/pageton/gotg/adapter"
	"github.com/pageton/gotg/types"
)

type ChatUnion interface {
	int | int64 | string
}

func getIdByUnion[chatUnion ChatUnion](ctx *adapter.Context, chat chatUnion) (int64, error) {
	switch val := any(chat).(type) {
	case string:
		username := val
		peer := ctx.PeerStorage.GetPeerByUsername(username)
		if peer.ID != 0 {
			return peer.ID, nil
		}
		chat, err := ctx.ResolveUsername(username)
		return chat.GetID(), err
	case int64:
		return val, nil
	case int:
		return int64(val), nil
	}
	// Unreachable
	return 0, nil
}

// SendMessage is a generic helper for ext.Context.SendMessage method.
func SendMessage[chatUnion ChatUnion](ctx *adapter.Context, chat chatUnion, request *tg.MessagesSendMessageRequest) (*types.Message, error) {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return nil, err
	}

	return ctx.SendMessage(chatID, request)
}

// SendMedia is a generic helper for ext.Context.SendMedia method.
func SendMedia[chatUnion ChatUnion](ctx *adapter.Context, chat chatUnion, request *tg.MessagesSendMediaRequest) (*types.Message, error) {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return nil, err
	}

	return ctx.SendMedia(chatID, request)
}

// GetInlineBotResults is a generic helper for ext.Context.GetInlineBotResults method.
func GetInlineBotResults[chatUnion ChatUnion](ctx *adapter.Context, chat chatUnion, botUsername string, request *tg.MessagesGetInlineBotResultsRequest) (*tg.MessagesBotResults, error) {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return nil, err
	}

	return ctx.GetInlineBotResults(chatID, botUsername, request)
}

// SendInlineBotResult is a generic helper for ext.Context.SendInlineBotResult method.
func SendInlineBotResult[chatUnion ChatUnion](ctx *adapter.Context, chat chatUnion, request *tg.MessagesSendInlineBotResultRequest) (tg.UpdatesClass, error) {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return nil, err
	}

	return ctx.SendInlineBotResult(chatID, request)
}

// SendReaction is a generic helper for ext.Context.SendReaction method.
func SendReaction[chatUnion ChatUnion](ctx *adapter.Context, chat chatUnion, request *tg.MessagesSendReactionRequest) (*types.Message, error) {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return nil, err
	}

	return ctx.SendReaction(chatID, request)
}

// SendMultiMedia is a generic helper for ext.Context.SendMultiMedia method.
func SendMultiMedia[chatUnion ChatUnion](ctx *adapter.Context, chat chatUnion, request *tg.MessagesSendMultiMediaRequest) (*types.Message, error) {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return nil, err
	}

	return ctx.SendMultiMedia(chatID, request)
}

// EditMessage is a generic helper for ext.Context.EditMessage method.
func EditMessage[chatUnion ChatUnion](ctx *adapter.Context, chat chatUnion, request *tg.MessagesEditMessageRequest) (*types.Message, error) {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return nil, err
	}

	return ctx.EditMessage(chatID, request)
}

// GetChat is a generic helper for ext.Context.GetChat method.
func GetChat[chatUnion ChatUnion](ctx *adapter.Context, chat chatUnion) (tg.ChatFullClass, error) {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return nil, err
	}

	return ctx.GetChat(chatID)
}

// GetUser is a generic helper for ext.Context.GetUser method.
func GetUser[chatUnion ChatUnion](ctx *adapter.Context, user chatUnion) (*tg.UserFull, error) {

	userID, err := getIdByUnion(ctx, user)
	if err != nil {
		return nil, err
	}

	return ctx.GetUser(userID)
}

// GetMessages is a generic helper for ext.Context.GetMessages method.
func GetMessages[chatUnion ChatUnion](ctx *adapter.Context, chat chatUnion, messageIds []tg.InputMessageClass) ([]tg.MessageClass, error) {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return nil, err
	}

	return ctx.GetMessages(chatID, messageIds)
}

// BanChatMember is a generic helper for ext.Context.BanChatMember method.
func BanChatMember[chatUnion ChatUnion](ctx *adapter.Context, chat, user chatUnion, untilDate int) (tg.UpdatesClass, error) {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return nil, err
	}

	userID, err := getIdByUnion(ctx, user)
	if err != nil {
		return nil, err
	}

	return ctx.BanChatMember(chatID, userID, untilDate)
}

// UnbanChatMember is a generic helper for ext.Context.UnbanChatMember method.
func UnbanChatMember[chatUnion ChatUnion](ctx *adapter.Context, chat, user chatUnion) (bool, error) {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return false, err
	}

	userID, err := getIdByUnion(ctx, user)
	if err != nil {
		return false, err
	}

	return ctx.UnbanChatMember(chatID, userID)
}

// AddChatMembers is a generic helper for ext.Context.AddChatMembers method.
func AddChatMembers[chatUnion ChatUnion](ctx *adapter.Context, chat chatUnion, userIDs []int64, forwardLimit int) (bool, error) {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return false, err
	}

	return ctx.AddChatMembers(chatID, userIDs, forwardLimit)
}

// DeleteMessages is a generic helper for ext.Context.DeleteMessages method.
func DeleteMessages[chatUnion ChatUnion](ctx *adapter.Context, chat chatUnion, messageIDs []int) error {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return err
	}

	return ctx.DeleteMessages(chatID, messageIDs)
}

// PromoteChatMember is a generic helper for ext.Context.PromoteChatMember method.
func PromoteChatMember[chatUnion ChatUnion](ctx *adapter.Context, chat, user chatUnion, opts *adapter.EditAdminOpts) (bool, error) {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return false, err
	}

	userID, err := getIdByUnion(ctx, user)
	if err != nil {
		return false, err
	}

	return ctx.PromoteChatMember(chatID, userID, opts)
}

// DemoteChatMember is a generic helper for ext.Context.DemoteChatMember method.
func DemoteChatMember[chatUnion ChatUnion](ctx *adapter.Context, chat, user chatUnion, opts *adapter.EditAdminOpts) (bool, error) {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return false, err
	}

	userID, err := getIdByUnion(ctx, user)
	if err != nil {
		return false, err
	}

	return ctx.DemoteChatMember(chatID, userID, opts)
}

// GetUserProfilePhotos is a generic helper for ext.Context.GetUserProfilePhotos method.
func GetUserProfilePhotos[chatUnion ChatUnion](ctx *adapter.Context, user chatUnion, opts *tg.PhotosGetUserPhotosRequest) ([]tg.PhotoClass, error) {

	userID, err := getIdByUnion(ctx, user)
	if err != nil {
		return nil, err
	}

	return ctx.GetUserProfilePhotos(userID, opts)
}

// TransferStarGift is a generic helper for ext.Context.TransferStarGift method.
func TransferStarGift[chatUnion ChatUnion](ctx *adapter.Context, chat chatUnion, starGift tg.InputSavedStarGiftClass) (tg.UpdatesClass, error) {

	chatID, err := getIdByUnion(ctx, chat)
	if err != nil {
		return nil, err
	}

	return ctx.TransferStarGift(chatID, starGift)
}
